POST http://localhost/api-qr-tandem/v1/create-qr.php
Content-Type: "application/json"

{
    "data": "referencia",
    "nombre_ref": "referencia",
    "description": "referencia",
    "created_by": 3
}