POST http://localhost/api-qr-tandem/v1/register-user.php
Content-Type: "application/json"

{
  "nombre":"Gerente aplicacion",
  "departamento":"El Escorial",
  "email":"gerente@gmail.com",
  "password":"asdf"
}